image: Visual Studio 2017
before_build:
  - dotnet restore
build:
  publish_nuget: true
  verbosity: normal
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
